const FETCH_OFFERS = "FETCH_OFFERS";
const FETCH_OFFERS_REJECTED = "FETCH_OFFERS_REJECTED";
const FETCH_OFFERS_FULFILLED = "FETCH_OFFERS_FULFILLED";
const ADD_OFFER = "ADD_OFFER";
const UPDATE_OFFER = "UPDATE_OFFER";
const DELETE_OFFER = "DELETE_OFFER";

export default {
  FETCH_OFFERS,
  FETCH_OFFERS_REJECTED,
  FETCH_OFFERS_FULFILLED,
  ADD_OFFER,
  UPDATE_OFFER,
  DELETE_OFFER,
};
