const FETCH_USER = "FETCH_USER";
const FETCH_USER_FULFILLED = "FETCH_USER_FULFILLED";
const FETCH_USER_REJECTED = "FETCH_USER_REJECTED";

const ADD_USER = "ADD_USER";
const ADD_USER_FULFILLED = "ADD_USER_FULFILLED";
const ADD_USER_REJECTED = "ADD_USER_REJECTED";

const UPDATE_USER = "UPDATE_USER";
const UPDATE_USER_FULFILLED = "UPDATE_USER_FULFILLED";
const UPDATE_USER_REJECTED = "UPDATE_USER_REJECTED";

const DELETE_USER = "DELETE_USER";
const DELETE_USER_FULFILLED = "DELETE_USER_FULFILLED";
const DELETE_USER_REJECTED = "DELETE_USER_REJECTED";

const FORM_SUBMITION_STATUS = "FORM_SUBMITION_STATUS";

export default {
  FETCH_USER,
  FETCH_USER_FULFILLED,
  FETCH_USER_REJECTED,

  ADD_USER,
  ADD_USER_FULFILLED,
  ADD_USER_REJECTED,

  UPDATE_USER,
  UPDATE_USER_FULFILLED,
  UPDATE_USER_REJECTED,

  DELETE_USER,
  DELETE_USER_FULFILLED,
  DELETE_USER_REJECTED,

  FORM_SUBMITION_STATUS,
};
